version: 2
updates:
  # Enable version updates for npm
  - package-ecosystem: "npm"
    # Look for `package.json` and `package-lock.json` in the `root` directory
    directory: "/"
    # Check for updates once a week
    schedule:
      interval: "weekly"
      # Check for updates on Monday
      day: "monday"
    # Assign PRs to the @dependencies team
    assignees:
      - "@your-team"
    # Add labels to pull requests for npm
    labels:
      - "dependencies"
      - "javascript"
    # Set the versioning strategy for npm
    versioning-strategy: increase
    # Open pull requests for security updates immediately
    open-pull-requests-limit: 10
    # Only allow updates to the lockfile for patch versions
    versioning-strategy: increase-if-necessary
    # Automatically merge minor and patch updates that pass CI
    commit-message:
      prefix: "chore(deps)"
      prefix-development: "chore(dev-deps)"
    # Group updates by dependency name
    groups:
      npm-dependencies:
        patterns:
          - "*"
        update-types: ["version-update:semver-patch", "version-update:semver-minor"]
      npm-dev-dependencies:
        patterns:
          - "*"
        dependency-type: "development"
        update-types: ["version-update:semver-patch", "version-update:semver-minor"]
      npm-security-updates:
        update-types: ["version-update:semver-patch", "version-update:semver-minor", "version-update:semver-major"]
        dependency-type: "all"
        update-types: ["security"]
