import * as React from 'react';
import { createContext, useContext, useState, useEffect } from 'react';

type Language = 'es' | 'en';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

const translations = {
  es: {
    // Auth
    'auth.title': 'PRMCMS',
    'auth.subtitle': 'Sistema de Gestión de Paquetes',
    'auth.email': 'Correo electrónico',
    'auth.password': 'Contraseña',
    'auth.rememberMe': 'Recordarme',
    'auth.login': 'Iniciar sesión',
    'auth.welcome': 'Bienvenido',
    'auth.resetPassword': 'Restablecer Contraseña',
    'auth.resetPasswordDescription': 'Ingresa tu correo electrónico para recibir instrucciones de restablecimiento',
    'auth.resetSuccess': 'Correo Enviado',
    'auth.resetEmailSent': 'Se ha enviado un correo de restablecimiento',
    'auth.resetError': 'Error al Enviar',
    'auth.unknownError': 'Error desconocido',
    'auth.checkEmailInstructions': 'Revisa tu bandeja de entrada para las instrucciones',
    'auth.backToLogin': 'Volver al Inicio de Sesión',
    'auth.emailPlaceholder': 'tu.correo@ejemplo.com',
    'auth.sending': 'Enviando...',
    'auth.sendResetLink': 'Enviar Enlace de Restablecimiento',
    
    // Dashboard
    'dashboard.goodMorning': 'Buenos días',
    'dashboard.goodAfternoon': 'Buenas tardes',
    'dashboard.goodEvening': 'Buenas noches',
    'dashboard.todayStats': 'Estadísticas de hoy',
    'dashboard.packagesReceived': 'Paquetes recibidos',
    'dashboard.pendingDeliveries': 'Entregas pendientes',
    'dashboard.recentActivity': 'Actividad reciente',
    
    // Actions
    'actions.receivePackages': 'Recibir Paquetes',
    'actions.search': 'Buscar',
    'actions.deliver': 'Entregar',
    'actions.customers': 'Clientes',
    
    // Package Intake
    'intake.title': 'Recepción de Paquetes',
    'intake.scanBarcode': 'Escanear código de barras',
    'intake.trackingNumber': 'Número de seguimiento',
    'intake.carrier': 'Transportista',
    'intake.customer': 'Cliente',
    'intake.packageSize': 'Tamaño del paquete',
    'intake.specialHandling': 'Manejo especial',
    'intake.saveAndNotify': 'Guardar y notificar',
    'intake.small': 'Pequeño',
    'intake.medium': 'Mediano',
    'intake.large': 'Grande',
    
    // Customers
    'customers.title': 'Directorio de Clientes',
    'customers.search': 'Buscar cliente...',
    'customers.addNew': 'Agregar nuevo cliente',
    'customers.name': 'Nombre',
    'customers.mailbox': 'Buzón',
    'customers.phone': 'Teléfono',
    'customers.activePackages': 'Paquetes activos',
    
    // Communications
    'communications.title': 'Comunicaciones',
    'communications.search': 'Buscar comunicaciones...',
    'communications.compose': 'Redactar',
    'communications.all': 'Todos',
    'communications.email': 'Correo',
    'communications.sms': 'SMS',
    'communications.whatsapp': 'WhatsApp',
    'communications.recentCommunications': 'Comunicaciones Recientes',
    'communications.quickActions': 'Acciones Rápidas',
    'communications.sendBulkEmail': 'Enviar Correo Masivo',
    'communications.sendBulkSMS': 'Enviar SMS Masivo',
    'communications.broadcastWhatsApp': 'Difundir WhatsApp',
    'communications.templates': 'Plantillas',
    'communications.statistics': 'Estadísticas de Comunicación',
    'communications.sent': 'Enviado',
    'communications.pending': 'Pendiente',
    'communications.failed': 'Fallido',
    'communications.totalSent': 'Total Enviados',
    'communications.openRate': 'Tasa de Apertura',
    'communications.responseRate': 'Tasa de Respuesta',
    'communications.filter': 'Filtrar',
    'communications.noFound': 'No se encontraron comunicaciones',
    'communications.adjustSearch': 'Intenta ajustar tu búsqueda o filtros',
    'communications.backToDashboard': 'Volver al Panel',
    
    // Devices
    'devices.title': 'Gestión de Dispositivos y Activos',
    'devices.totalDevices': 'Total de Dispositivos',
    'devices.active': 'Activos',
    'devices.maintenance': 'Mantenimiento',
    'devices.lowBattery': 'Batería Baja',
    'devices.totalValue': 'Valor Total',
    'devices.alerts': 'Alertas',
    'devices.search': 'Buscar dispositivos...',
    'devices.allStatus': 'Todos los Estados',
    'devices.allTypes': 'Todos los Tipos',
    'devices.export': 'Exportar',
    'devices.addDevice': 'Agregar Dispositivo',
    'devices.deviceOverview': 'Resumen de Dispositivos',
    'devices.liveMonitoring': 'Monitoreo en vivo activo',
    'devices.criticalAlerts': 'Alertas Críticas Requieren Atención',
    'devices.criticalAlertDesc': 'alerta(s) crítica(s) necesitan atención inmediata',
    'devices.viewAlerts': 'Ver Alertas',
    'devices.batteryStatus': 'Estado de Batería de Dispositivos Móviles',
    'devices.devicesMonitored': 'dispositivos monitoreados',
    'devices.battery': 'Batería',
    'devices.health': 'Salud',
    'devices.inventory': 'Inventario',
    'devices.mobileDevices': 'Dispositivos Móviles',
    'devices.assetTracking': 'Rastreo de Activos',
    'devices.printers': 'Impresoras',
    'devices.fleet': 'Flota',
    'devices.inactive': 'Inactivo',
    'devices.repair': 'Reparación',
    'devices.retired': 'Retirado',
    'devices.lost': 'Perdido',
    'devices.tablets': 'Tabletas',
    'devices.smartphones': 'Teléfonos Inteligentes',
    'devices.scanners': 'Escáneres',
    'devices.laptops': 'Portátiles',
    'devices.vehicles': 'Vehículos',
    'devices.gpsTrackers': 'Rastreadores GPS',
    'devices.cameras': 'Cámaras',
    'devices.sensors': 'Sensores',
    'devices.iotDevices': 'Dispositivos IoT',
    'devices.temperature': 'Temperatura',
    'devices.humidity': 'Humedad',
    'devices.location': 'Ubicación',
    'devices.lastUpdate': 'Última Actualización',
    'devices.signalStrength': 'Intensidad de Señal',
    'devices.dataUsage': 'Uso de Datos',
    'devices.deviceStatus': 'Estado del Dispositivo',
    'devices.deviceMonitoring': 'Monitoreo de Dispositivos',
    'devices.deviceManagement': 'Gestión de Dispositivos',
    'devices.refresh': 'Actualizar',
    'devices.configure': 'Configurar',
    'devices.diagnose': 'Diagnosticar',
    'devices.updateFirmware': 'Actualizar Firmware',
    'devices.reboot': 'Reiniciar',
    'devices.scheduleMaintenace': 'Programar Mantenimiento',
    'devices.viewHistory': 'Ver Historial',
    'devices.generateReport': 'Generar Reporte',
    
    // Common
    'common.save': 'Guardar',
    'common.cancel': 'Cancelar',
    'common.loading': 'Cargando...',
    'common.error': 'Error',
    'common.success': 'Éxito',
    'common.logout': 'Cerrar sesión',
    
    // Security
    'security.title': 'Centro de Seguridad',
    'security.description': 'Gestiona la seguridad de tu cuenta y configuración de autenticación',
    'security.changePassword': 'Cambiar Contraseña',
    'security.changePasswordDescription': 'Actualiza tu contraseña para mantener tu cuenta segura',
    'security.currentPassword': 'Contraseña Actual',
    'security.newPassword': 'Nueva Contraseña',
    'security.confirmPassword': 'Confirmar Contraseña',
    'security.updatePassword': 'Actualizar Contraseña',
    'security.updating': 'Actualizando...',
    'security.passwordMismatch': 'Contraseñas No Coinciden',
    'security.passwordsDoNotMatch': 'Las contraseñas no coinciden',
    'security.passwordTooShort': 'Contraseña Muy Corta',
    'security.passwordMinLength': 'La contraseña debe tener al menos 8 caracteres',
    'security.passwordUpdated': 'Contraseña Actualizada',
    'security.passwordUpdateSuccess': 'Tu contraseña ha sido actualizada exitosamente',
    'security.passwordUpdateError': 'Error al Actualizar Contraseña',
    'security.twoFactorAuth': 'Autenticación de Dos Factores',
    'security.twoFactorDescription': 'Añade una capa extra de seguridad a tu cuenta',
    'security.twoFactorStatus': 'Estado de 2FA',
    'security.twoFactorActive': 'Autenticación de dos factores activa',
    'security.twoFactorInactive': 'Autenticación de dos factores inactiva',
    'security.enabled': 'Habilitado',
    'security.disabled': 'Deshabilitado',
    'security.setupTwoFactor': 'Configurar Autenticación de Dos Factores',
    'security.enterVerificationCode': 'Ingresa el código de verificación de 6 dígitos',
    'security.verificationCode': 'Código de Verificación',
    'security.verifying': 'Verificando...',
    'security.verify': 'Verificar',
    'security.cancel': 'Cancelar',
    'security.twoFactorEnabled': 'Autenticación de dos factores habilitada',
    'security.twoFactorSetupSuccess': 'La autenticación de dos factores ha sido configurada exitosamente',
    'security.twoFactorDisabled': 'Autenticación de Dos Factores Deshabilitada',
    'security.twoFactorDisableSuccess': 'La autenticación de dos factores ha sido deshabilitada',
    'security.twoFactorSetupError': 'Error al Configurar 2FA',
    'security.invalidCode': 'Código Inválido',
    'security.enterValidCode': 'Por favor ingresa un código válido de 6 dígitos',
    'security.securityStatus': 'Estado de Seguridad',
    'security.accountVerified': 'Cuenta Verificada',
    'security.emailVerified': 'Correo electrónico verificado',
    'security.verified': 'Verificado',
    'security.lastLogin': 'Último Inicio de Sesión',
    'security.never': 'Nunca',
    'security.active': 'Activo',
  },
  en: {
    // Auth
    'auth.title': 'PRMCMS',
    'auth.subtitle': 'Package Management System',
    'auth.email': 'Email',
    'auth.password': 'Password',
    'auth.rememberMe': 'Remember me',
    'auth.login': 'Login',
    'auth.welcome': 'Welcome',
    'auth.resetPassword': 'Reset Password',
    'auth.resetPasswordDescription': 'Enter your email to receive reset instructions',
    'auth.resetSuccess': 'Email Sent',
    'auth.resetEmailSent': 'Password reset email has been sent',
    'auth.resetError': 'Send Error',
    'auth.unknownError': 'Unknown error',
    'auth.checkEmailInstructions': 'Check your inbox for instructions',
    'auth.backToLogin': 'Back to Login',
    'auth.emailPlaceholder': 'your.email@example.com',
    'auth.sending': 'Sending...',
    'auth.sendResetLink': 'Send Reset Link',
    
    // Dashboard
    'dashboard.goodMorning': 'Good morning',
    'dashboard.goodAfternoon': 'Good afternoon', 
    'dashboard.goodEvening': 'Good evening',
    'dashboard.todayStats': "Today's stats",
    'dashboard.packagesReceived': 'Packages received',
    'dashboard.pendingDeliveries': 'Pending deliveries',
    'dashboard.recentActivity': 'Recent activity',
    
    // Actions
    'actions.receivePackages': 'Receive Packages',
    'actions.search': 'Search',
    'actions.deliver': 'Deliver',
    'actions.customers': 'Customers',
    
    // Package Intake
    'intake.title': 'Package Intake',
    'intake.scanBarcode': 'Scan barcode',
    'intake.trackingNumber': 'Tracking number',
    'intake.carrier': 'Carrier',
    'intake.customer': 'Customer',
    'intake.packageSize': 'Package size',
    'intake.specialHandling': 'Special handling',
    'intake.saveAndNotify': 'Save and notify',
    'intake.small': 'Small',
    'intake.medium': 'Medium',
    'intake.large': 'Large',
    
    // Customers
    'customers.title': 'Customer Directory',
    'customers.search': 'Search customer...',
    'customers.addNew': 'Add new customer',
    'customers.name': 'Name',
    'customers.mailbox': 'Mailbox',
    'customers.phone': 'Phone',
    'customers.activePackages': 'Active packages',
    
    // Communications
    'communications.title': 'Communications',
    'communications.search': 'Search communications...',
    'communications.compose': 'Compose',
    'communications.all': 'All',
    'communications.email': 'Email',
    'communications.sms': 'SMS',
    'communications.whatsapp': 'WhatsApp',
    'communications.recentCommunications': 'Recent Communications',
    'communications.quickActions': 'Quick Actions',
    'communications.sendBulkEmail': 'Send Bulk Email',
    'communications.sendBulkSMS': 'Send Bulk SMS',
    'communications.broadcastWhatsApp': 'Broadcast WhatsApp',
    'communications.templates': 'Templates',
    'communications.statistics': 'Communication Stats',
    'communications.sent': 'Sent',
    'communications.pending': 'Pending',
    'communications.failed': 'Failed',
    'communications.totalSent': 'Total Sent',
    'communications.openRate': 'Open Rate',
    'communications.responseRate': 'Response Rate',
    'communications.filter': 'Filter',
    'communications.noFound': 'No communications found',
    'communications.adjustSearch': 'Try adjusting your search or filters',
    'communications.backToDashboard': 'Back to Dashboard',
    
    // Devices
    'devices.title': 'Device & Asset Management',
    'devices.totalDevices': 'Total Devices',
    'devices.active': 'Active',
    'devices.maintenance': 'Maintenance',
    'devices.lowBattery': 'Low Battery',
    'devices.totalValue': 'Total Value',
    'devices.alerts': 'Alerts',
    'devices.search': 'Search devices...',
    'devices.allStatus': 'All Status',
    'devices.allTypes': 'All Types',
    'devices.export': 'Export',
    'devices.addDevice': 'Add Device',
    'devices.deviceOverview': 'Device Overview',
    'devices.liveMonitoring': 'Live monitoring active',
    'devices.criticalAlerts': 'Critical Alerts Require Attention',
    'devices.criticalAlertDesc': 'critical alert(s) need immediate attention',
    'devices.viewAlerts': 'View Alerts',
    'devices.batteryStatus': 'Mobile Device Battery Status',
    'devices.devicesMonitored': 'devices monitored',
    'devices.battery': 'Battery',
    'devices.health': 'Health',
    'devices.inventory': 'Inventory',
    'devices.mobileDevices': 'Mobile Devices',
    'devices.assetTracking': 'Asset Tracking',
    'devices.printers': 'Printers',
    'devices.fleet': 'Fleet',
    'devices.inactive': 'Inactive',
    'devices.repair': 'Repair',
    'devices.retired': 'Retired',
    'devices.lost': 'Lost',
    'devices.tablets': 'Tablets',
    'devices.smartphones': 'Smartphones',
    'devices.scanners': 'Scanners',
    'devices.laptops': 'Laptops',
    'devices.vehicles': 'Vehicles',
    'devices.gpsTrackers': 'GPS Trackers',
    'devices.cameras': 'Cameras',
    'devices.sensors': 'Sensors',
    'devices.iotDevices': 'IoT Devices',
    'devices.temperature': 'Temperature',
    'devices.humidity': 'Humidity',
    'devices.location': 'Location',
    'devices.lastUpdate': 'Last Update',
    'devices.signalStrength': 'Signal Strength',
    'devices.dataUsage': 'Data Usage',
    'devices.deviceStatus': 'Device Status',
    'devices.deviceMonitoring': 'Device Monitoring',
    'devices.deviceManagement': 'Device Management',
    'devices.refresh': 'Refresh',
    'devices.configure': 'Configure',
    'devices.diagnose': 'Diagnose',
    'devices.updateFirmware': 'Update Firmware',
    'devices.reboot': 'Reboot',
    'devices.scheduleMaintenace': 'Schedule Maintenance',
    'devices.viewHistory': 'View History',
    'devices.generateReport': 'Generate Report',
    
    // Common
    'common.save': 'Save',
    'common.cancel': 'Cancel',
    'common.loading': 'Loading...',
    'common.error': 'Error',
    'common.success': 'Success',
    'common.logout': 'Logout',
    
    // Security
    'security.title': 'Security Center',
    'security.description': 'Manage your account security and authentication settings',
    'security.changePassword': 'Change Password',
    'security.changePasswordDescription': 'Update your password to keep your account secure',
    'security.currentPassword': 'Current Password',
    'security.newPassword': 'New Password',
    'security.confirmPassword': 'Confirm Password',
    'security.updatePassword': 'Update Password',
    'security.updating': 'Updating...',
    'security.passwordMismatch': 'Passwords Do Not Match',
    'security.passwordsDoNotMatch': 'The passwords do not match',
    'security.passwordTooShort': 'Password Too Short',
    'security.passwordMinLength': 'Password must be at least 8 characters long',
    'security.passwordUpdated': 'Password Updated',
    'security.passwordUpdateSuccess': 'Your password has been updated successfully',
    'security.passwordUpdateError': 'Error Updating Password',
    'security.twoFactorAuth': 'Two-Factor Authentication',
    'security.twoFactorDescription': 'Add an extra layer of security to your account',
    'security.twoFactorStatus': '2FA Status',
    'security.twoFactorActive': 'Two-factor authentication active',
    'security.twoFactorInactive': 'Two-factor authentication inactive',
    'security.enabled': 'Enabled',
    'security.disabled': 'Disabled',
    'security.setupTwoFactor': 'Setup Two-Factor Authentication',
    'security.enterVerificationCode': 'Enter the 6-digit verification code',
    'security.verificationCode': 'Verification Code',
    'security.verifying': 'Verifying...',
    'security.verify': 'Verify',
    'security.cancel': 'Cancel',
    'security.twoFactorEnabled': 'Two-factor authentication enabled',
    'security.twoFactorSetupSuccess': 'Two-factor authentication has been set up successfully',
    'security.twoFactorDisabled': 'Two-Factor Authentication Disabled',
    'security.twoFactorDisableSuccess': 'Two-factor authentication has been disabled',
    'security.twoFactorSetupError': 'Error Setting Up 2FA',
    'security.invalidCode': 'Invalid Code',
    'security.enterValidCode': 'Please enter a valid 6-digit code',
    'security.securityStatus': 'Security Status',
    'security.accountVerified': 'Account Verified',
    'security.emailVerified': 'Email verified',
    'security.verified': 'Verified',
    'security.lastLogin': 'Last Login',
    'security.never': 'Never',
    'security.active': 'Active',
  }
};

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [language, setLanguage] = useState<Language>('es');

  useEffect(() => {
    const saved = localStorage.getItem('prmcms-language') as Language;
    if (saved && (saved === 'es' || saved === 'en')) {
      setLanguage(saved);
    }
  }, []);

  const handleSetLanguage = (lang: Language) => {
    setLanguage(lang);
    localStorage.setItem('prmcms-language', lang);
  };

  const t = (key: string): string => {
    return translations[language][key as keyof typeof translations['es']] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage: handleSetLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}