# Scheduled OWASP Dependency and Vulnerability Scan
# @date 2025-02-14
name: OWASP Dependency Scan

on:
  schedule:
    - cron: '0 0 * * 0'
  workflow_dispatch:

jobs:
  dependency-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run OWASP Dependency Check
        uses: dependency-check/DependencyCheck_Action@main
        with:
          project: 'caribe-mail-connect'
          path: '.'
          format: 'SARIF'
          out: 'reports'
      - name: NPM Audit
        run: npm audit --audit-level=moderate || true
      - name: Upload report
        uses: actions/upload-artifact@v4
        with:
          name: owasp-dependency-report
          path: reports
